language: node_js
node_js:
  - '0.10'
language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
